---
title: "Chicago Budget"
author: "Michael Molloy"
date: "6/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r include=FALSE}
library(tidyverse)
```
```{r include=FALSE}
# read data
budget_2011 <- read_csv("../../source/chicago_budget/Budget_-_2011_Budget_Ordinance_-_Positions_and_Salaries.csv") %>% mutate(YEAR = 2011)
budget_2012 <- read_csv("../../source/chicago_budget/Budget_-_2012_Budget_Ordinance_-_Positions_and_Salaries.csv") %>% mutate(YEAR = 2012)
budget_2013 <- read_csv("../../source/chicago_budget/Budget_-_2013_Budget_Ordinance_-_Positions_and_Salaries.csv") %>% mutate(YEAR = 2013)
budget_2014 <- read_csv("../../source/chicago_budget/Budget_-_2014_Budget_Ordinance_-_Positions_and_Salaries.csv") %>% mutate(YEAR = 2014)
budget_2015 <- read_csv("../../source/chicago_budget/Budget_-_2015_Budget_Ordinance_-_Positions_and_Salaries.csv") %>% mutate(YEAR = 2015)
budget_2016 <- read_csv("../../source/chicago_budget/Budget_-_2016_Budget_Ordinance_-_Positions_and_Salaries.csv") %>% mutate(YEAR = 2016)
budget_2017 <- read_csv("../../source/chicago_budget/Budget_-_2017_Budget_Ordinance_-_Positions_and_Salaries.csv") %>% mutate(YEAR = 2017)
budget_2018 <- read_csv("../../source/chicago_budget/Budget_-_2018_Budget_Ordinance_-_Positions_and_Salaries.csv") %>% mutate(YEAR = 2018)
budget_2019 <- read_csv("../../source/chicago_budget/Budget_-_2019_Budget_Ordinance_-_Positions_and_Salaries.csv") %>% mutate(YEAR = 2019)
```

```{r eval=FALSE, include=FALSE}
# Column names don't match across datasets. Need to identify which ones are missing and for which years so we can create them.

  # get all the column names for each dataset
  data_names <- data.frame(name = names(budget_2011), year = 2011) %>% 
    rbind(data.frame(name = names(budget_2012), year = 2012)) %>%
    rbind(data.frame(name = names(budget_2013), year = 2013)) %>% 
    rbind(data.frame(name = names(budget_2014), year = 2014)) %>% 
    rbind(data.frame(name = names(budget_2015), year = 2015)) %>% 
    rbind(data.frame(name = names(budget_2016), year = 2016)) %>% 
    rbind(data.frame(name = names(budget_2017), year = 2017)) %>% 
    rbind(data.frame(name = names(budget_2018), year = 2018)) %>% 
    rbind(data.frame(name = names(budget_2019), year = 2019))
  
# identify the columns that don't show up in all years
data_names_issues <- data_names %>% 
  group_by(name) %>% 
  summarize(count=n()) %>% 
  filter(count < 9)
# show the years the troublesome columns DO show up in
data_names %>% 
  filter(name %in% data_names_issues$name) %>% 
arrange(name) %>% View()
```

```{r}
# add columns to years where they're missing
  #2011
budget_2011$`BARGAINING UNIT` <- NA
names(budget_2011)[names(budget_2011)=="DEPARTMENT NAME"] <- "DEPARTMENT DESCRIPTION"
names(budget_2011)[names(budget_2011)=="DIVISION NAME"] <- "DIVISION DESCRIPTION"
names(budget_2011)[names(budget_2011)=="FUND NAME"] <- "FUND DESCRIPTION"
names(budget_2011)[names(budget_2011)=="SECTION NAME"] <- "SECTION DESCRIPTION"
names(budget_2011)[names(budget_2011)=="SCHEDULE"] <- "SCHEDULE / GRADE"
names(budget_2011)[names(budget_2011)=="TOTAL BUDGETED UNITS"] <- "TOTAL BUDGETED UNIT"
names(budget_2011)[names(budget_2011)=="SUBSECTION CODE"] <- "SUB-SECTION CODE"
names(budget_2011)[names(budget_2011)=="SUBSECTION NAME"] <- "SUB-SECTION DESCRIPTION"
budget_2011 <- within(budget_2011,rm("DEPARTMENT"))

  #2012
names(budget_2012)[names(budget_2012)=="DEPARTMENT NUMBER"] <- "DEPARTMENT CODE"
names(budget_2012)[names(budget_2012)=="SCHEDULE/GRADE"] <- "SCHEDULE / GRADE"

  #2011-2013
budget_2011$`ORGANIZATION DESCRIPTION` <- NA
budget_2012$`ORGANIZATION DESCRIPTION` <- NA
budget_2013$`ORGANIZATION DESCRIPTION` <- NA

# bind together
budget <- rbind(budget_2011,budget_2012,budget_2013,budget_2014,budget_2015,budget_2016,budget_2017,budget_2018,budget_2019)
```

```{r}
# calculate the total budget by year
budget_summary <- budget %>%
  group_by(YEAR) %>% 
  summarize(total =sum(`TOTAL BUDGETED AMOUNT`)/1000000000) %>% #calculate total budget and simplify
  mutate(growth = 100*(total - lag(total))/lag(total)) # how much did the budget grow from previous year?

# chart of total budget over time
budget_summary %>% 
  ggplot(aes(YEAR,total)) +
  geom_line() +
  scale_x_continuous(breaks = c(2011:2019)) +
  labs(title = "Chicago Government Employee Salary Budget", y="Dollars (in Billions",x="")

# chart of year over year budget growth rate
budget_summary %>%
  ggplot(aes(YEAR,growth)) +
  geom_line() +
  geom_smooth(method="lm") +
  scale_x_continuous(breaks = c(2011:2019)) +
  labs(title = "Chicago Government Employee Salary Budget", y="Dollars (in Billions",x="")
```

```{r}

```


